// generated by stringer -type=operator; DO NOT EDIT

package haddoque

import "fmt"

const _operator_name = "opUnknownopAndopOropLteopGteopLtopGtopEqopNeq"

var _operator_index = [...]uint8{0, 9, 14, 18, 23, 28, 32, 36, 40, 45}

func (i operator) String() string {
	if i < 0 || i+1 >= operator(len(_operator_index)) {
		return fmt.Sprintf("operator(%d)", i)
	}
	return _operator_name[_operator_index[i]:_operator_index[i+1]]
}
