// generated by stringer -type=token; DO NOT EDIT

package haddoque

import "fmt"

const _token_name = "tokErrortokEOFtokWhitespacetokFieldtokIdentifiertokLiteralsBegintokBooltokChartokStringtokNumbertokLiteralsEndtokLparentokRparentokLbrackettokRbrackettokCommatokKeywordsBegintokWheretokAndtokOrtokIntokContainstokKeywordsEndtokOperatorsBegintokLttokLtetokGttokGtetokEqtokNeqtokNottokOperatorsEnd"

var _token_index = [...]uint16{0, 8, 14, 27, 35, 48, 64, 71, 78, 87, 96, 110, 119, 128, 139, 150, 158, 174, 182, 188, 193, 198, 209, 223, 240, 245, 251, 256, 262, 267, 273, 279, 294}

func (i token) String() string {
	if i < 0 || i+1 >= token(len(_token_index)) {
		return fmt.Sprintf("token(%d)", i)
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
