// generated by stringer -type=token; DO NOT EDIT

package haddoque

import "fmt"

const _token_name = "tokErrortokEOFtokWhitespacetokFieldtokIdentifiertokBooltokChartokStringtokNumbertokLparentokRparentokLbrackettokRbrackettokCommatokWheretokAndtokOrtokIntokContainstokLttokLtetokGttokGtetokEqtokNeqtokNot"

var _token_index = [...]uint8{0, 8, 14, 27, 35, 48, 55, 62, 71, 80, 89, 98, 109, 120, 128, 136, 142, 147, 152, 163, 168, 174, 179, 185, 190, 196, 202}

func (i token) String() string {
	if i < 0 || i+1 >= token(len(_token_index)) {
		return fmt.Sprintf("token(%d)", i)
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
